// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview A mental health chat AI agent.
 *
 * - mentalHealthChat - A function that handles the mental health chat process.
 * - MentalHealthChatInput - The input type for the mentalHealthChat function.
 * - MentalHealthChatOutput - The return type for the mentalHealthChat function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MentalHealthChatInputSchema = z.object({
  userInput: z.string().describe('The user input for the mental health chat.'),
});
export type MentalHealthChatInput = z.infer<typeof MentalHealthChatInputSchema>;

const MentalHealthChatOutputSchema = z.object({
  response: z.string().describe('The response from the mental health chat AI.'),
});
export type MentalHealthChatOutput = z.infer<typeof MentalHealthChatOutputSchema>;

export async function mentalHealthChat(input: MentalHealthChatInput): Promise<MentalHealthChatOutput> {
  return mentalHealthChatFlow(input);
}

const prompt = ai.definePrompt({
  name: 'mentalHealthChatPrompt',
  input: {schema: MentalHealthChatInputSchema},
  output: {schema: MentalHealthChatOutputSchema},
  prompt: `You are a supportive and empathetic AI chatbot designed to provide initial mental health support and guidance.

  Respond to the user's input with understanding and offer suggestions for appropriate resources. You are available 24/7.

  Input: {{{userInput}}}
  `,
});

const mentalHealthChatFlow = ai.defineFlow(
  {
    name: 'mentalHealthChatFlow',
    inputSchema: MentalHealthChatInputSchema,
    outputSchema: MentalHealthChatOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
