// This is an autogenerated file from Firebase Studio.
'use client';

import {useState} from 'react';
import Image from 'next/image';
import {PageHeader} from '@/components/page-header';
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Upload, FileText, X, QrCode} from 'lucide-react';

export default function QrHealthCardPage() {
  const [uploadedFiles, setUploadedFiles] = useState<File[]>([]);
  const [qrCode, setQrCode] = useState<string | null>(null);

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      setUploadedFiles(prevFiles => [...prevFiles, ...Array.from(event.target.files!)]);
    }
  };

  const removeFile = (index: number) => {
    setUploadedFiles(prevFiles => prevFiles.filter((_, i) => i !== index));
  };

  const handleGenerateQr = () => {
    // In a real application, you would process the files and generate a QR code
    // with the relevant data. For now, we'll use a placeholder.
    setQrCode('https://picsum.photos/seed/qr-code/256/256');
  };

  return (
    <div className="space-y-8 w-full p-4 sm:p-6 lg:p-8">
      <PageHeader
        title="Generate QR Health Card"
        description="Create a personal QR code for your health information."
      />
      <div className="grid gap-8 lg:grid-cols-2">
        <Card className="flex flex-col">
          <CardHeader>
            <CardTitle>Upload Your Medical Documents</CardTitle>
            <CardDescription>
              Select the documents you want to include in your QR Health Card.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex-1 space-y-4">
            <label
              htmlFor="file-upload"
              className="flex cursor-pointer flex-col items-center justify-center rounded-lg border-2 border-dashed border-border p-8 text-center hover:bg-accent/50 transition-colors"
            >
              <Upload className="mb-2 h-8 w-8 text-muted-foreground" />
              <span className="font-semibold">Click to upload documents</span>
              <span className="text-sm text-muted-foreground">
                PDF, JPG, PNG, etc.
              </span>
            </label>
            <Input
              id="file-upload"
              type="file"
              multiple
              className="sr-only"
              onChange={handleFileChange}
            />

            {uploadedFiles.length > 0 && (
              <div className="space-y-2">
                <h4 className="font-medium">Uploaded Files:</h4>
                <ul className="space-y-2 max-h-48 overflow-y-auto">
                  {uploadedFiles.map((file, index) => (
                    <li
                      key={index}
                      className="flex items-center justify-between rounded-md border p-2"
                    >
                      <div className="flex items-center gap-2">
                        <FileText className="h-5 w-5 text-muted-foreground shrink-0" />
                        <span className="text-sm truncate">{file.name}</span>
                      </div>
                      <Button
                        variant="ghost"
                        size="icon"
                        className="h-6 w-6 shrink-0"
                        onClick={() => removeFile(index)}
                      >
                        <X className="h-4 w-4" />
                      </Button>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </CardContent>
          <CardFooter>
            <Button onClick={handleGenerateQr} disabled={uploadedFiles.length === 0} className="w-full sm:w-auto">
              <QrCode className="mr-2 h-4 w-4" />
              Generate QR Code
            </Button>
          </CardFooter>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Your Health QR Code</CardTitle>
            <CardDescription>
              Scan this code to access your uploaded documents.
            </CardDescription>
          </CardHeader>
          <CardContent className="flex items-center justify-center min-h-80">
            {qrCode ? (
              <div className="text-center space-y-4">
                <Image
                  src={qrCode}
                  alt="Health QR Code"
                  width={256}
                  height={256}
                  className="rounded-lg mx-auto border"
                  data-ai-hint="qr code"
                />
                <Button variant="outline" size="sm">Download QR Code</Button>
              </div>
            ) : (
              <div className="flex h-64 w-64 flex-col items-center justify-center rounded-lg bg-muted text-center text-muted-foreground">
                <QrCode className="mb-4 h-12 w-12" />
                <p className="text-sm px-4">Your QR code will appear here after you upload documents and click 'Generate'.</p>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}